project:
  type: website
  output-dir: _site

website:
  title: "Data & Stories of Thi Lan Anh Tran"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: posts/index.qmd
      - text: About
        href: about.qmd
    right:
      - text: About
        href: about.qmd
      - icon: github
        aria-label: GitHub
        href: https://github.com/ttra0196

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    number-sections: false
    smooth-scroll: true
    code-copy: true
